### PR TITLE
Various PID improvements

### PR DESCRIPTION
**Pull request by arihant2math**
- Moved all the motor specific data to one class.
- Cut down on code repetition.

EDIT: All has been merged, hopefully this doesn't blow up during testing.

### CODE REVIEW

**Review by albonec — CHANGES_REQUESTED** [review]
Invert the signs in the directionSign. Everything else seems ok for now

**Comment by arihant2math** [comment]
> Invert the signs in the directionSign. Everything else seems ok for now

directionSign is non existent now? Check again.

**Comment by arihant2math** [comment]
Tests are failing due to a syntax issue, do not merge yet.

**Comment by arihant2math** [comment]
Tests pass locally

**Comment by arihant2math** [comment]
Testing complete, merging

**Pull request merged**
